### ISSUE TITLE
Where does the contents.csv come from?

### ISSUE THREAD

**Issue by kuhlaid** [epierson9/pain-disparities#7]
Hi @epierson9,
I'm working with your code once again for a project. I can't figure out the `contents.csv` file. It looks like the code is reading a pre-populated CSV file, but is this one you generate yourself or was found in an OAI archive? It sounds like an OAI provided file but it does not appear in my archives (which have probably changed considerably since you downloaded the OAI archives). I know you have this function call commented out but was just wondering.

https://github.com/epierson9/pain-disparities/blob/15d6139d5d16f50770482c1d338ee1d358dbd9a5/image_processing.py#L531

- thank you

On a side note, since I am working with a set of radiograph images with DICOM headers that differ from OAI images, I am planning to create what is probably similar to the `contents.csv` file and would contain the radiograph metadata of images being processed. I will use this instead of reading the DICOM headers as done below so I can create an easier way to use radiograph metadata in the image processing script, regardless of what your DICOM headers look like. Bulk updating the headers of thousands of DICOM images seemed out of my reach.
https://github.com/epierson9/pain-disparities/blob/4edf970e35804c128168c08e9a0beaa1b4a994d9/image_processing.py#L374

**Comment by epierson9** [comment]
Hey! Yeah, you shouldn't need to use this file to process the images. I don't have access to the original dataset right now, but as I recall it was just a CSV which listed the images, which was included with my version of the data. I compared to it as a sanity check. But as you note it isn't necessary to process these or other DICOM files.
