### ISSUE TITLE
image processing

### ISSUE THREAD

**Issue by hxu105** [epierson9/pain-disparities#9]
Howdy, thank you for sharing this amazing work. However, I do face difficulties in getting the data. I was not able to download data from [NDA query tools](https://nda.nih.gov/oai/querying_oai_data_in_nda.html), due to the NDA download manager issue ( I think that might be NDA's issues), and if I use OAICompleteData_ASCII, will that be sufficient to reproduce the paper experiments? Many thanks!

**Comment by epierson9** [comment]
Thanks for your interest! You’ll need to download the image data as well,
not just CSVs - so whatever data you download should be on the order of a
couple terabytes. (I’m not familiar with the latest data format hosted on
the OAI website, sorry.)

**Comment by hxu105** [comment]
Thank you! I think I am going to report an issue to NDA.

**Comment by hxu105** [comment]
Hi, 

sorry for bothering again. I have downloaded the OAI data from NIH, and I am not sure whether I have the correct dataset. I downloaded images from [this site](https://nda.nih.gov/oai/accessing_images) and there would be a zip file containing all the image and a binary file (sorry for not knowing the file type). And for doing the image_processing.py, is there no need to specify the dataset directory? I check the code, and there is not arguments for defining raw data directory? 

Many thanks!

**Comment by epierson9** [comment]
Please see the main README in this directory for information about how to set paths and run code!

**Comment by hxu105** [comment]
Thanks, and if I get it correctly, set paths are step 3 which are after the data processing. I am still facing some problem in data processing step.

I download the OAI30MonthImages, which looks like this 
<img width="300" alt="image" src="https://github.com/epierson9/pain-disparities/assets/40327643/0b00a97f-117c-4979-b22f-cc2559a62eee">
And I want to do the data processing for 30m.zip (4.G.1 is the unzipped directory for 30m.zip), do I need to move my data to the same directory of image_processing.py?

Thanks!
